export const pipelineNames = [
 'Aardvark'
,'Aardwolf'
,'Abyssinian'
,'Addax'
,'Affenpinscher'
,'Aidi'
,'Ainu'
,'Airedoodle'
,'Akbash'
,'Akita'
,'Alabai'
,'Albatross'
,'Alligator'
,'Alpaca'
,'Alusky'
,'Anaconda'
,'Anchovies'
,'Angelfish'
,'Anglerfish'
,'Ant'
,'Anteater'
,'Antelope'
,'Ape'
,'Arapaima'
,'Armadillo'
,'Armyworm'
,'Asp'
,'Aurochs'
,'Aussiedoodle'
,'Aussiedor'
,'Avocet'
,'Axolotl'
,'American Alsatian'
,'Aye Aye'
,'Arizona Bark Scorpion'
,'Ambrosia Beetle'
,'Asiatic Black Bear'
,'Arizona Black Rattlesnake'
,'Assassin Bug'
,'American Bulldog'
,'Australian Bulldog'
,'African Bullfrog'
,'African Bush Elephant'
,'Australian Cattle Dog'
,'African Civet'
,'African Clawed Frog'
,'American Cocker Spaniel'
,'American Cockroach'
,'Asian Cockroach'
,'Australian Cockroach'
,'American Coonhound'
,'Alpine Dachsbracke'
,'Appenzeller Dog'
,'American Dog Tick'
,'Asian Elephant'
,'American Eskimo Dog'
,'Angora Ferret'
,'Arafura File Snake'
,'African Forest Elephant'
,'Arctic Fox'
,'American Foxhound'
,'Alligator Gar'
,'Australian Gecko'
,'Asian Giant Hornet'
,'Aldabra Giant Tortoise'
,'Alpine Goat'
,'Angora Goat'
,'African Grey Parrot'
,'American Hairless Terrier'
,'Arctic Hare'
,'Apple Head Chihuahua'
,'Afghan Hound'
,'Alaskan Husky'
,'Australian Kelpie Dog'
,'Alaskan Klee Kai'
,'Australian Labradoodle'
,'Amur Leopard'
,'American Leopard Hound'
,'Agama Lizard'
,'Anole Lizard'
,'Armadillo Lizard'
,'Alaskan Malamute'
,'Australian Mist'
,'African Palm Civet'
,'Asian Palm Civet'
,'Amazon Parrot'
,'Adelie Penguin'
,'African Penguin'
,'American Pit Bull Terrier'
,'American Pygmy Goat'
,'Australian Retriever'
,'Amazon River Dolphin (Pink Dolphin)'
,'American Robin'
,'Antarctic scale worm'
,'Akita Shepherd'
,'Alaskan Shepherd'
,'Australian Shepherd'
,'Anatolian Shepherd Dog'
,'Aesculapian snake'
,'American Staffordshire Terrier'
,'Airedale Terrier'
,'Australian Terrier'
,'American Toad'
,'African Tree Toad'
,'Albacore Tuna'
,'American Water Spaniel'
,'African Wild Dog'
,'Arctic Wolf'
];
